---
- name: File and copy modules
  hosts: web
  gather_facts: no
  tasks:
   - name: create file
     file:
      path: /home/ec2-user/sample.txt
      state: touch
      
   - name: copy contents
     copy:
      content: "THis is a sample text for Ansible"
      dest: /home/ec2-user/sample.txt
      
      
  
